version: '{build}'
image: Visual Studio 2017
platform:
  - x86
  - x64
services:
  - mssql2016
# - postgresql
# - mysql
#environment:
#  global:
#    TEST_DBMS_SQLServer: true
branches:
  except: 
    - gh-pages
install:
  - ps: |
      Write-Host ("PROCESSOR_ARCHITECTURE = {0}" -f $env:PROCESSOR_ARCHITECTURE)
  - ps: |
      (Get-PSProvider 'FileSystem').Home = 'c:\projects\'
      iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      scoop update
      scoop install openjdk
      #scoop install ant
      #scoop install maven
      scoop install scala
      scoop install sbt
      # Following software are installed by default <https://www.appveyor.com/docs/build-environment/#pre-installed-software>
      # - JDK8
      # - Maven
  - cmd: |
      SET JAVA_HOME=C:\Users\appveyor\scoop\apps\openjdk\current\bin
      SET PATH=%JAVA_HOME%\bin;%PATH%
      SET M2_HOME=%USERPROFILE%\.m2
      where java
      SET 
build_script:
  - sbt compile
test_script:
  - sbt test
  - ps: Get-ChildItem $env:USERPROFILE
after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $files = Get-ChildItem '.\target\test-reports\TEST-*.xml'
      foreach ($file in $files) {
          (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))
      }
on_success:
  - sbt executable
cache:
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.ivy\cache'
  - '%USERPROFILE%\.sbt\boot'
  - '%USERPROFILE%\.embedmysql'
  - '%USERPROFILE%\.embedpostgresql'
#  - '%LocalAppData%\scoop            -> appveyor.yml'
#  - '%USERPROFILE%\.m2               -> appveyor.yml'
#  - '%USERPROFILE%\.ivy2             -> appveyor.yml'
#  - '%USERPROFILE%\.embedmysql       -> appveyor.yml'
#  - '%USERPROFILE%\.embedpostgresql  -> appveyor.yml'
artifacts:
  - path: 'target\executable\gitbucket.war'
  - path: 'target\executable\gitbucket.md5'
  - path: 'target\executable\gitbucket.sha1'
  - path: 'target\executable\gitbucket.sha256'
