version: '{build}'
os: Windows Server 2016
services:
  - mssql2016
  - postgresql
  - mysql
environment:
  global:
    - TEST_DBMS_SQLServer: true
branches:
  except: 
    - gh-pages
install:
  - ps: |
      (get-psprovider 'FileSystem').Home = 'c:\projects\'
      iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      # scoop bucket add extras
      scoop update
      scoop install -y ant
      scoop install -y scala
      scoop install -y sbt
      # Followin software are installed by default <https://www.appveyor.com/docs/build-environment/#pre-installed-software>
      # - JDK8
      # - Maven
  - cmd: |
      SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
      SET PATH=%JAVA_HOME%\bin;%PATH%
      SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
      SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
      SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
      SET 
build_script:
  - sbt clean compile
test_script:
  - sbt test
on_success:
  - sbt executable
cache:
  - C:\Users\appveyor\AppData\Local\scoop
  - C:\Users\appveyor\.m2   -> appveyor.yml
  - C:\Users\appveyor\.ivy2 -> appveyor.yml
artifacts:
  - path: 'target\executable\gitbucket.war'
  - path: 'target\executable\gitbucket.md5'
  - path: 'target\executable\gitbucket.sha1'
  - path: 'target\executable\gitbucket.sha256'
