version: '{build}'
image: Visual Studio 2017
services:
#  - mssql2016
# - postgresql
# - mysql
#environment:
#  global:
#    TEST_DBMS_SQLServer: true
branches:
  except: 
    - gh-pages
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - ps: |
      Write-Host ("PROCESSOR_ARCHITECTURE = {0}" -f $env:PROCESSOR_ARCHITECTURE)
      net user /add TestUser Password!
      net localgroup Administrators Testuser /add
  - ps: |
      (Get-PSProvider 'FileSystem').Home = 'c:\projects\'
      iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
      scoop update
      #scoop install openjdk
      #scoop install ant
      #scoop install maven
      scoop install scala
      scoop install sbt
      # Following software are installed by default <https://www.appveyor.com/docs/build-environment/#pre-installed-software>
      # - JDK8
      # - Maven
  - cmd: |
      SET JAVA_HOME=%ProgramFiles%\Java\jdk1.8.0
      SET PATH=%JAVA_HOME%\bin;%PATH%
      SET M2_HOME=%USERPROFILE%\.m2
      SET 
build_script:
#  - sbt compile
  - ps: |
      $p = Start-Process "sbt" -ArgumentList "compile" -PassThru -Wait
      return $p.ExitCode
test_script:
#  - sbt test
  - ps: |
      $p = Start-Process "sbt" -ArgumentList "test" -PassThru -Wait
      return $p.ExitCode
after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $files = Get-ChildItem '.\target\test-reports\TEST-*.xml'
      foreach ($file in $files) {
          (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))
      }
on_success:
  - sbt executable
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
cache:
  - 'C:\Users\appveyor\.coursier'
  - 'C:\Users\appveyor\.ivy\cache'
  - 'C:\Users\appveyor\.sbt\boot'
  - 'C:\Users\TestUser\.coursier'
  - 'C:\Users\TestUser\.ivy\cache'
  - 'C:\Users\TestUser\.sbt\boot'
  - 'C:\Users\TestUser\.embedmysql'
  - 'C:\Users\TestUser\.embedpostgresql'
  
  
#  - '%LocalAppData%\scoop            -> appveyor.yml'
#  - '%USERPROFILE%\.m2               -> appveyor.yml'
#  - '%USERPROFILE%\.ivy2             -> appveyor.yml'
#  - '%USERPROFILE%\.embedmysql       -> appveyor.yml'
#  - '%USERPROFILE%\.embedpostgresql  -> appveyor.yml'
artifacts:
  - path: 'target\executable\gitbucket.war'
  - path: 'target\executable\gitbucket.md5'
  - path: 'target\executable\gitbucket.sha1'
  - path: 'target\executable\gitbucket.sha256'
